// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-liCirmvIDlCJyV8qPGGUvcUdNTmrnQM',
    appId: '1:527773746265:web:577aec17b546ae87689d48',
    messagingSenderId: '527773746265',
    projectId: 'comchat-ae2c9',
    authDomain: 'comchat-ae2c9.firebaseapp.com',
    storageBucket: 'comchat-ae2c9.firebasestorage.app',
    measurementId: 'G-7HN88NDXV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKTSnGlHB1RZ8pUUtAfG2lb4m6lutvoA',
    appId: '1:527773746265:android:427096c81ab244a0689d48',
    messagingSenderId: '527773746265',
    projectId: 'comchat-ae2c9',
    storageBucket: 'comchat-ae2c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsCJPNLwvVU7JdmLOFoRu14zyg8T9WxlI',
    appId: '1:527773746265:ios:a18a60e8a98e7ef0689d48',
    messagingSenderId: '527773746265',
    projectId: 'comchat-ae2c9',
    storageBucket: 'comchat-ae2c9.firebasestorage.app',
    iosClientId: '527773746265-ej8njujjm1fk02gcsqh05pd986rka1jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.comchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsCJPNLwvVU7JdmLOFoRu14zyg8T9WxlI',
    appId: '1:527773746265:ios:a18a60e8a98e7ef0689d48',
    messagingSenderId: '527773746265',
    projectId: 'comchat-ae2c9',
    storageBucket: 'comchat-ae2c9.firebasestorage.app',
    iosClientId: '527773746265-ej8njujjm1fk02gcsqh05pd986rka1jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.comchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-liCirmvIDlCJyV8qPGGUvcUdNTmrnQM',
    appId: '1:527773746265:web:2a667daa7e4b2ef4689d48',
    messagingSenderId: '527773746265',
    projectId: 'comchat-ae2c9',
    authDomain: 'comchat-ae2c9.firebaseapp.com',
    storageBucket: 'comchat-ae2c9.firebasestorage.app',
    measurementId: 'G-362KNF0JMK',
  );

}